import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MultiRangeSlider from '../components/MultiRangeSlider'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row w-full min-h-screen">
        <div className="basis-3/4 flex justify-center items-center">here is map</div>
        <div className="basis-1/4 flex flex-col bg-gray-200 px-4 py-2">
          <div className="text-2xl text-center py-2">Filter</div>
          <div className="py-2">
            <fieldset>
              <legend className="text-base py-2">Country/Region</legend>
              <div className="flex flex-row flex-wrap gap-[4%]">
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="taiwan" name="country" value="taiwan" />
                  <label htmlFor="coding">Taiwan</label>
                </div>
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="hong kong" name="country" value="hong kong" />
                  <label htmlFor="music">Hong Kong</label>
                </div>
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="china" name="country" value="china" />
                  <label htmlFor="music">China</label>
                </div>
              </div>
            </fieldset>
          </div>
          <div className="py-2">
            <legend className="text-base py-2">Period</legend>
            <MultiRangeSlider min={0} max={60 * 24}
              onChange={(min, max) => console.log(min, max)}
              format={val => {
                const hour = (Math.floor(val / 60)).toString().padStart(2, '0')
                const minute = (val % 60).toString().padStart(2, '0')
                return `${hour}:${minute}`
              }}/>
          </div>
        </div>
      </main>
    </div>
  )
}
