import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row w-full h-screen">
        <div className="basis-3/4 w-full h-full flex justify-center items-center">here is map</div>
        <div className="basis-1/4 w-full h-full flex flex-col bg-gray-200 px-4 py-2">
          <div className="text-2xl text-center py-2">Filter</div>
          <div className="py-2">
            <fieldset>
              <legend className="text-base py-2">Country/Region</legend>
              <div className="flex flex-row flex-wrap gap-[4%]">
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="taiwan" name="country" value="taiwan" />
                  <label htmlFor="coding">Taiwan</label>
                </div>
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="hong kong" name="country" value="hong kong" />
                  <label htmlFor="music">Hong Kong</label>
                </div>
                <div className="flex gap-1 items-baseline basis-[48%]">
                  <input type="checkbox" id="china" name="country" value="china" />
                  <label htmlFor="music">China</label>
                </div>
              </div>
            </fieldset>
          </div>
          <div className="py-2">
            <legend className="text-base py-2">Period</legend>
            <input type="range" className="min-w-full" min="1" max="100" id="myRange"></input>
          </div>
        </div>
      </main>
    </div>
  )
}
